"""
AEOS Agent PR Proposal Generator — deterministic, read-only.

No LLM. No network. No secrets. No .env.
Reads the project registry and MemoryRecords, produces a structured PR proposal.
Every output is marked read_only: true · applied: false.
"""

from __future__ import annotations

import json
from dataclasses import dataclass, field
from datetime import UTC, datetime
from pathlib import Path

PR_PROPOSAL_MODE = "deterministic read-only planner"

_SAFETY_CONSTRAINTS = [
    "No secrets or credentials included in the PR",
    "No .env files modified or committed",
    "No production database migration",
    "Staging review required before any production apply",
    "Human approval required at each gate",
    "No autonomous apply — each action requires explicit human sign-off",
]

_OUT_OF_SCOPE_ALWAYS = [
    "Production deployment or production migration",
    "Credential rotation (must be done separately, not committed)",
    "New product features unrelated to risk remediation",
    "Changes to ~/.aeos/ or the project registry",
    "Any automated or batch apply without prior human review",
]


# ---------------------------------------------------------------------------
# Data model
# ---------------------------------------------------------------------------


@dataclass
class PRProposal:
    """Deterministic PR proposal for a single registered project."""

    project_name: str
    generated_at: str
    agent_mode: str
    title: str
    objective: str
    why_now: list[str]
    recommended_scope: list[str]
    out_of_scope: list[str]
    likely_files: list[str]
    safety_constraints: list[str]
    implementation_steps: list[str]
    validation_commands: list[str]
    approval_checklist: list[str]
    risks: list[str]
    rollback_notes: list[str]
    evidence_references: dict[str, object]
    read_only: bool = True
    applied: bool = False
    human_validation_required: bool = True
    final_statement: str = field(
        default="No changes were applied. This is a proposal only."
    )


# ---------------------------------------------------------------------------
# Decision helpers
# ---------------------------------------------------------------------------


def _build_title(
    name: str,
    critical: int,
    important: int,
    generated: int,
    control_level: str,
    production_ready: bool,
) -> str:
    if critical > 0:
        return (
            f"security: validate RLS hardening and resolve "
            f"{critical} critical finding(s) for {name}"
        )
    if generated > 0:
        return (
            f"security: stage {generated} SQL hardening block(s) "
            f"and validate {name} on staging"
        )
    if important > 0:
        return (
            f"security: address {important} important finding(s) "
            f"and staging validation for {name}"
        )
    if control_level == "weak":
        return (
            f"governance: strengthen project control "
            f"and document sovereignty policy for {name}"
        )
    if not production_ready:
        return f"security: resolve remaining production blockers for {name}"
    return f"docs: release readiness review for {name}"


def _build_objective(
    critical: int,
    important: int,
    generated: int,
    production_ready: bool,
) -> str:
    if critical > 0:
        return (
            f"Resolve {critical} critical security finding(s) that currently block "
            "production deployment. Review generated SQL hardening blocks, obtain "
            "human sign-off on each critical risk, and validate on staging before "
            "any production apply."
        )
    if generated > 0:
        return (
            f"Stage and validate {generated} SQL hardening block(s) generated by "
            "AEOS. Apply to the staging environment, run the validation suite, and "
            "document results. Do not apply to production without sign-off."
        )
    if important > 0:
        return (
            f"Address {important} important security and sovereignty finding(s). "
            "Review findings, implement agreed mitigations, validate on staging, "
            "and update documentation."
        )
    if not production_ready:
        return (
            "Resolve remaining production blockers identified by AEOS. "
            "Review all open findings, complete manual actions, and validate "
            "the project is ready for production deployment."
        )
    return (
        "Document the current project state and prepare release readiness "
        "evidence. No critical findings remain — this PR focuses on "
        "documentation, governance, and evidence pack updates."
    )


def _build_why_now(
    critical: int,
    important: int,
    generated: int,
    manual: int,
    production_ready: bool,
) -> list[str]:
    reasons: list[str] = []
    if critical > 0:
        reasons.append(
            f"{critical} critical finding(s) are blocking production deployment"
        )
    if generated > 0:
        reasons.append(
            f"{generated} SQL hardening block(s) are pending staging review and apply"
        )
    if important > 0:
        reasons.append(
            f"{important} important security/sovereignty finding(s) remain unaddressed"
        )
    if manual > 0:
        reasons.append(
            f"{manual} manual action(s) require explicit human decision and execution"
        )
    if not production_ready:
        reasons.append(
            "Project is NOT READY FOR PRODUCTION — "
            "remediation required before any production deployment"
        )
    if not reasons:
        reasons.append("Routine documentation and release readiness review")
    return reasons


def _build_scope(
    critical: int,
    important: int,
    generated: int,
    manual: int,
    providers: list[str],
    production_ready: bool,
) -> list[str]:
    scope: list[str] = []
    has_supabase = "supabase" in [p.lower() for p in providers]

    if critical > 0:
        scope.append(
            f"Review and document each of the {critical} critical finding(s) — "
            "with explicit human decision on each"
        )

    if generated > 0 and has_supabase:
        scope.append(
            f"Review and apply {generated} SQL hardening block(s) to the "
            "staging Supabase instance — NOT production"
        )
        scope.append(
            "Validate RLS policies on staging: test data access patterns, "
            "verify no query regressions"
        )
    elif generated > 0:
        scope.append(
            f"Review and stage {generated} hardening block(s) — "
            "human review required before any apply"
        )

    if manual > 0:
        scope.append(
            f"Complete {manual} manual action(s) as listed in the AEOS hardening report"
        )

    if important > 0:
        scope.append(
            f"Review the {important} important finding(s) and create a "
            "prioritised remediation plan"
        )

    scope.append(
        "Update governance documentation in docs/governance/ or docs/evidence/"
    )
    scope.append(
        "Regenerate evidence pack after changes: "
        "aeos workspace demo --output-dir <path> --overwrite"
    )

    return scope


def _build_likely_files(
    providers: list[str],
    evidence_dir: Path | None,
) -> list[str]:
    files: list[str] = []
    has_supabase = "supabase" in [p.lower() for p in providers]

    if has_supabase:
        files.append("supabase/migrations/<new-rls-hardening>.sql (candidate)")
        files.append("docs/governance/RLS-HARDENING-REVIEW.md (candidate)")

    files.append("docs/evidence/<project-name>/ (candidate)")
    files.append("docs/development/QUALITY-GATE.md (candidate)")
    files.append("Any docs/governance/ file documenting human decisions (candidate)")

    if evidence_dir is not None and evidence_dir.exists():
        files.append(f"{evidence_dir}/ (confirmed — evidence_dir exists on disk)")

    return files


def _build_implementation_steps(
    critical: int,
    important: int,
    generated: int,
    manual: int,
    providers: list[str],
    project_name: str,
) -> list[str]:
    steps: list[str] = []
    has_supabase = "supabase" in [p.lower() for p in providers]
    n = 1

    steps.append(
        f"{n}. Run `aeos agent plan --project {project_name}` to confirm "
        "current state before any changes"
    )
    n += 1

    if critical > 0:
        steps.append(
            f"{n}. Review each of the {critical} critical finding(s) individually "
            "and document a human decision for each"
        )
        n += 1

    if generated > 0 and has_supabase:
        steps.append(
            f"{n}. Review all {generated} SQL hardening block(s) from the "
            "AEOS hardening report — understand each before applying"
        )
        n += 1
        steps.append(
            f"{n}. Apply SQL blocks to the local / staging Supabase instance "
            "using `supabase migration up` — staging only, not production"
        )
        n += 1
        steps.append(
            f"{n}. Validate RLS policies: run the existing test suite and "
            "verify data access patterns manually"
        )
        n += 1
    elif generated > 0:
        steps.append(
            f"{n}. Review generated hardening block(s) and stage them — "
            "human review required before any apply"
        )
        n += 1

    if manual > 0:
        steps.append(
            f"{n}. Complete {manual} manual action(s) documented in the "
            "hardening report — each requires explicit human execution"
        )
        n += 1

    if important > 0:
        steps.append(
            f"{n}. Review the {important} important finding(s) and create a "
            "remediation plan for each"
        )
        n += 1

    steps.append(f"{n}. Update documentation: docs/governance/ or docs/evidence/")
    n += 1

    steps.append(
        f"{n}. Run `aeos workspace demo` to regenerate the evidence pack "
        "with updated state"
    )
    n += 1

    steps.append(
        f"{n}. Re-run `aeos agent plan --project {project_name}` to confirm "
        "the plan status has improved"
    )
    n += 1

    steps.append(
        f"{n}. Obtain human sign-off on every approval checklist item before merge"
    )

    return steps


def _build_validation_commands(
    project_name: str,
    memory_dir: Path,
) -> list[str]:
    return [
        "git status",
        f"aeos agent plan --project {project_name}",
        "aeos reclaim harden --path <project-path> --json",
        "aeos workspace demo --output-dir /tmp/aeos-workspace-demo --overwrite",
        (
            f"aeos ui evidence-pack "
            f"--memory-dir {memory_dir} "
            f"--project {project_name} "
            f"--output-dir /tmp/ep-{project_name}"
        ),
    ]


def _build_approval_checklist(
    critical: int,
    important: int,
    generated: int,
    manual: int,
) -> list[str]:
    checklist: list[str] = []

    if critical > 0:
        checklist.append(
            f"[ ] All {critical} critical finding(s) reviewed — "
            "human decision documented for each"
        )

    if generated > 0:
        checklist.append(
            f"[ ] All {generated} SQL hardening block(s) reviewed and "
            "applied to staging (not production)"
        )
        checklist.append("[ ] Staging validation passed — no data access regressions")

    if manual > 0:
        checklist.append(
            f"[ ] All {manual} manual action(s) completed or explicitly deferred"
        )

    checklist.extend(
        [
            "[ ] No secrets or credentials included in this PR",
            "[ ] No .env files modified or committed",
            "[ ] No production migration included",
            "[ ] CTO / lead has reviewed and approved",
            "[ ] Evidence pack regenerated after changes: aeos workspace demo",
        ]
    )

    return checklist


def _build_risks(
    critical: int,
    important: int,
    generated: int,
    control_level: str,
    providers: list[str],
) -> list[str]:
    risks: list[str] = []
    has_supabase = "supabase" in [p.lower() for p in providers]

    if generated > 0 and has_supabase:
        risks.append(
            "RLS migration may affect existing queries — "
            "test thoroughly on staging before any production apply"
        )
        risks.append(
            "Missing profile data (e.g. commune_id) could cause RLS policies "
            "to reject valid users after migration"
        )

    if critical > 0:
        risks.append(
            f"{critical} critical finding(s) remain — production deployment "
            "blocked until each is explicitly resolved"
        )

    if important > 0:
        risks.append(
            f"{important} important finding(s) may contain security implications "
            "not yet fully assessed"
        )

    if control_level == "weak":
        risks.append(
            "Project control level is 'weak' — portability and secrets "
            "policy not fully enforced"
        )

    risks.append(
        "Staging changes not reverted before production rollout could "
        "introduce inconsistencies"
    )

    return risks


def _build_rollback(
    generated: int,
    providers: list[str],
) -> list[str]:
    notes: list[str] = []
    has_supabase = "supabase" in [p.lower() for p in providers]

    if generated > 0 and has_supabase:
        notes.append(
            "Staging only: use `supabase migration revert` or restore from "
            "a staging snapshot if issues are found"
        )
        notes.append(
            "Keep SQL hardening blocks on a separate branch until staging "
            "validation is complete"
        )

    notes.extend(
        [
            "All documentation changes are reversible via `git revert`",
            "Evidence pack can be regenerated at any time: "
            "`aeos workspace demo --overwrite`",
            "No production changes proposed in this PR — "
            "production rollback not applicable",
        ]
    )

    return notes


# ---------------------------------------------------------------------------
# Core generator (no registry — memory_dir provided directly)
# ---------------------------------------------------------------------------


def generate_pr_proposal_from_memory(
    project_name: str,
    memory_dir: Path,
) -> PRProposal:
    """Generate a PR proposal directly from a memory directory.

    Does not require a registry. Used by workspace and evidence-pack renderers
    which already have memory_dir available. Pure read — no writes, no network.
    No LLM. No .env.
    """
    from aeos.memory.timeline import load_project_records

    record_count = 0
    critical = 0
    important = 0
    manual = 0
    generated = 0
    control_level = "unknown"
    providers: list[str] = []
    latest_record_id: str | None = None

    try:
        records = load_project_records(memory_dir, project_name)
        record_count = len(records)
        if records:
            latest = records[-1]
            fs = latest.findings_summary
            critical = fs.get("critical", 0)
            important = fs.get("important", 0)
            manual = fs.get("manual", 0)
            generated = fs.get("generated", 0)
            control_level = latest.control_level
            providers = latest.providers
            latest_record_id = latest.record_id
    except (FileNotFoundError, ValueError):
        pass

    production_ready = critical == 0 and generated == 0

    title = _build_title(
        project_name, critical, important, generated, control_level, production_ready
    )
    objective = _build_objective(critical, important, generated, production_ready)
    why_now = _build_why_now(critical, important, generated, manual, production_ready)
    scope = _build_scope(
        critical, important, generated, manual, providers, production_ready
    )
    impl_steps = _build_implementation_steps(
        critical, important, generated, manual, providers, project_name
    )
    val_cmds = _build_validation_commands(project_name, memory_dir)
    checklist = _build_approval_checklist(critical, important, generated, manual)
    risks = _build_risks(critical, important, generated, control_level, providers)
    rollback = _build_rollback(generated, providers)
    likely_files = _build_likely_files(providers, None)

    evidence: dict[str, object] = {
        "record_count": record_count,
        "latest_record_id": latest_record_id,
        "evidence_dir": None,
        "production_ready": production_ready,
        "critical": critical,
        "important": important,
        "manual": manual,
        "generated_sql_blocks": generated,
        "control_level": control_level,
        "providers": providers,
        "registry_path": None,
    }

    return PRProposal(
        project_name=project_name,
        generated_at=datetime.now(tz=UTC).strftime("%Y-%m-%dT%H:%M:%SZ"),
        agent_mode=PR_PROPOSAL_MODE,
        title=title,
        objective=objective,
        why_now=why_now,
        recommended_scope=scope,
        out_of_scope=list(_OUT_OF_SCOPE_ALWAYS),
        likely_files=likely_files,
        safety_constraints=list(_SAFETY_CONSTRAINTS),
        implementation_steps=impl_steps,
        validation_commands=val_cmds,
        approval_checklist=checklist,
        risks=risks,
        rollback_notes=rollback,
        evidence_references=evidence,
    )


# ---------------------------------------------------------------------------
# Core generator (registry-based)
# ---------------------------------------------------------------------------


def generate_pr_proposal(
    project_name: str,
    registry_path: Path | None = None,
) -> PRProposal:
    """Generate a deterministic PR proposal for a registered project.

    Pure read — never writes files, never modifies the registry,
    never contacts any network endpoint. No LLM. No .env access.

    Raises FileNotFoundError if the registry does not exist.
    Raises ValueError if the project is not found in the registry.
    """
    from aeos.memory.timeline import load_project_records
    from aeos.project.registry import DEFAULT_REGISTRY, load_registry

    reg_path = registry_path if registry_path is not None else DEFAULT_REGISTRY

    if not reg_path.exists():
        raise FileNotFoundError(
            f"Registry not found: {reg_path}. Run 'aeos workspace init' to initialise."
        )

    registry = load_registry(reg_path)
    proj = next((p for p in registry.projects if p.name == project_name), None)
    if proj is None:
        known = [p.name for p in registry.projects] or ["(none)"]
        raise ValueError(
            f"Project '{project_name}' not found in registry. Known projects: {known}"
        )

    # Load MemoryRecords — graceful if memory_dir absent or empty
    record_count = 0
    critical = 0
    important = 0
    manual = 0
    generated = 0
    control_level = "unknown"
    providers: list[str] = []
    latest_record_id: str | None = None

    try:
        records = load_project_records(proj.memory_dir, project_name)
        record_count = len(records)
        if records:
            latest = records[-1]
            fs = latest.findings_summary
            critical = fs.get("critical", 0)
            important = fs.get("important", 0)
            manual = fs.get("manual", 0)
            generated = fs.get("generated", 0)
            control_level = latest.control_level
            providers = latest.providers
            latest_record_id = latest.record_id
    except (FileNotFoundError, ValueError):
        pass

    production_ready = critical == 0 and generated == 0

    title = _build_title(
        project_name, critical, important, generated, control_level, production_ready
    )
    objective = _build_objective(critical, important, generated, production_ready)
    why_now = _build_why_now(critical, important, generated, manual, production_ready)
    scope = _build_scope(
        critical, important, generated, manual, providers, production_ready
    )
    impl_steps = _build_implementation_steps(
        critical, important, generated, manual, providers, project_name
    )
    val_cmds = _build_validation_commands(project_name, proj.memory_dir)
    checklist = _build_approval_checklist(critical, important, generated, manual)
    risks = _build_risks(critical, important, generated, control_level, providers)
    rollback = _build_rollback(generated, providers)
    likely_files = _build_likely_files(providers, proj.evidence_dir)

    evidence: dict[str, object] = {
        "record_count": record_count,
        "latest_record_id": latest_record_id,
        "evidence_dir": str(proj.evidence_dir) if proj.evidence_dir else None,
        "production_ready": production_ready,
        "critical": critical,
        "important": important,
        "manual": manual,
        "generated_sql_blocks": generated,
        "control_level": control_level,
        "providers": providers,
        "registry_path": str(reg_path),
    }

    return PRProposal(
        project_name=project_name,
        generated_at=datetime.now(tz=UTC).strftime("%Y-%m-%dT%H:%M:%SZ"),
        agent_mode=PR_PROPOSAL_MODE,
        title=title,
        objective=objective,
        why_now=why_now,
        recommended_scope=scope,
        out_of_scope=list(_OUT_OF_SCOPE_ALWAYS),
        likely_files=likely_files,
        safety_constraints=list(_SAFETY_CONSTRAINTS),
        implementation_steps=impl_steps,
        validation_commands=val_cmds,
        approval_checklist=checklist,
        risks=risks,
        rollback_notes=rollback,
        evidence_references=evidence,
    )


# ---------------------------------------------------------------------------
# Terminal summary renderer
# ---------------------------------------------------------------------------


def render_pr_proposal_summary(proposal: PRProposal) -> str:
    lines: list[str] = []
    a = lines.append

    a("AEOS PR Proposal")
    a("")
    a(f"Mode:              {proposal.agent_mode}")
    a(f"Project:           {proposal.project_name}")
    a(f"Generated:         {proposal.generated_at}")
    ev = proposal.evidence_references
    a(f"Records:           {ev.get('record_count', 0)}")
    crit = ev.get("critical", 0)
    imp = ev.get("important", 0)
    gen = ev.get("generated_sql_blocks", 0)
    if crit or imp or gen:
        a(f"Findings:          critical={crit}  important={imp}  sql_blocks={gen}")
    a("")
    a(f"  Title:  {proposal.title}")
    a("")

    if proposal.why_now:
        a("  Why now:")
        for r in proposal.why_now:
            a(f"    ! {r}")
        a("")

    if proposal.recommended_scope:
        a("  Recommended scope:")
        for i, s in enumerate(proposal.recommended_scope[:4], 1):
            a(f"    {i}. {s}")
        if len(proposal.recommended_scope) > 4:
            remaining = len(proposal.recommended_scope) - 4
            a(f"    ... and {remaining} more — see --output for full proposal")
        a("")

    if proposal.validation_commands:
        a("  Validation commands:")
        for cmd in proposal.validation_commands[:3]:
            a(f"    → {cmd}")
        a("")

    a("  read_only: true  ·  applied: false  ·  human validation required")
    a(f"  {proposal.final_statement}")

    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Markdown renderer
# ---------------------------------------------------------------------------


def render_pr_proposal_markdown(proposal: PRProposal) -> str:
    lines: list[str] = []
    a = lines.append

    a("# AEOS PR Proposal")
    a("")
    a(f"**Project:** {proposal.project_name}")
    a(f"**Mode:** {proposal.agent_mode}")
    a(f"**Generated:** {proposal.generated_at}")
    a("")
    a("---")
    a("")

    # 1. Title
    a("## 1. Title")
    a("")
    a(f"**{proposal.title}**")
    a("")

    # 2. Objective
    a("## 2. Objective")
    a("")
    a(proposal.objective)
    a("")

    # 3. Why this PR now
    a("## 3. Why This PR Now")
    a("")
    for r in proposal.why_now:
        a(f"- {r}")
    a("")

    # 4. Recommended scope
    a("## 4. Recommended Scope")
    a("")
    for s in proposal.recommended_scope:
        a(f"- {s}")
    a("")

    # 5. Out of scope
    a("## 5. Out of Scope")
    a("")
    for s in proposal.out_of_scope:
        a(f"- {s}")
    a("")

    # 6. Likely files involved
    a("## 6. Likely Files Involved")
    a("")
    for f in proposal.likely_files:
        a(f"- `{f}`")
    a("")

    # 7. Safety constraints
    a("## 7. Safety Constraints")
    a("")
    for s in proposal.safety_constraints:
        a(f"- {s}")
    a("")

    # 8. Suggested implementation steps
    a("## 8. Suggested Implementation Steps")
    a("")
    for step in proposal.implementation_steps:
        a(step)
    a("")

    # 9. Validation commands
    a("## 9. Validation Commands")
    a("")
    a("```sh")
    for cmd in proposal.validation_commands:
        a(cmd)
    a("```")
    a("")

    # 10. Human approval checklist
    a("## 10. Human Approval Checklist")
    a("")
    for item in proposal.approval_checklist:
        a(f"- {item}")
    a("")

    # 11. Risks
    a("## 11. Risks")
    a("")
    for r in proposal.risks:
        a(f"- {r}")
    a("")

    # 12. Rollback notes
    a("## 12. Rollback Notes")
    a("")
    for note in proposal.rollback_notes:
        a(f"- {note}")
    a("")

    # 13. Evidence references
    a("## 13. Evidence References")
    a("")
    ev = proposal.evidence_references
    a("| Field | Value |")
    a("|-------|-------|")
    a(f"| record_count | {ev.get('record_count', 0)} |")
    a(f"| latest_record_id | `{ev.get('latest_record_id') or 'n/a'}` |")
    a(f"| evidence_dir | `{ev.get('evidence_dir') or 'not configured'}` |")
    a(f"| production_ready | {ev.get('production_ready', False)} |")
    a(f"| critical | {ev.get('critical', 0)} |")
    a(f"| important | {ev.get('important', 0)} |")
    a(f"| manual | {ev.get('manual', 0)} |")
    a(f"| generated_sql_blocks | {ev.get('generated_sql_blocks', 0)} |")
    a(f"| control_level | {ev.get('control_level', 'unknown')} |")
    a(f"| providers | {', '.join(ev.get('providers', []) or [])} |")  # type: ignore[arg-type]
    a(f"| registry_path | `{ev.get('registry_path', '')}` |")
    a("")

    # 14. Final statement
    a("## 14. Final Statement")
    a("")
    a(f"**{proposal.final_statement}**")
    a("")
    a("```")
    a("read_only: true  ·  applied: false  ·  human validation required")
    a("```")
    a("")

    return "\n".join(lines)


# ---------------------------------------------------------------------------
# JSON renderer
# ---------------------------------------------------------------------------


def render_pr_proposal_json(proposal: PRProposal) -> str:
    payload: dict[str, object] = {
        "project_name": proposal.project_name,
        "generated_at": proposal.generated_at,
        "agent_mode": proposal.agent_mode,
        "title": proposal.title,
        "objective": proposal.objective,
        "why_now": proposal.why_now,
        "recommended_scope": proposal.recommended_scope,
        "out_of_scope": proposal.out_of_scope,
        "likely_files": proposal.likely_files,
        "safety_constraints": proposal.safety_constraints,
        "implementation_steps": proposal.implementation_steps,
        "validation_commands": proposal.validation_commands,
        "approval_checklist": proposal.approval_checklist,
        "risks": proposal.risks,
        "rollback_notes": proposal.rollback_notes,
        "evidence_references": proposal.evidence_references,
        "read_only": proposal.read_only,
        "applied": proposal.applied,
        "human_validation_required": proposal.human_validation_required,
        "final_statement": proposal.final_statement,
    }
    return json.dumps(payload, indent=2)
